SELECT * FROM PlAN_GRAF_Z.PG_MEDICAMENT p WHERE p.POSITION_ID = 114049 AND p.MNN_NAME != (SELECT m.MNN_LIST_NAME FROM NOTIF_Z.MEDICINES m WHERE m.LOT_ID = 75842)
WHERE pgm.MNN_NAME != (SELECT m.MNN_LIST_NAME FROM NOTIF_Z.MEDICINES m WHERE m.LOT_ID = 75842)
pgm.MNN_NAME != nm.MNN_LIST_NAME
SELECT pgm.MNN_NAME, count(*) FROM PlAN_GRAPH_Z.PG_MEDICAMENT pgm WHERE pgm.POSITION_ID = 114049 GROUP BY pgm.MNN_NAME
SELECT m.MNN_LIST_NAME, count(*) FROM NOTIF_Z.MEDICINES m WHERE m.LOT_ID = 75842 GROUP BY m.MNN_LIST_NAME


SELECT * FROM
(SELECT pgm.MNN_NAME as NAME , count(*) AS c FROM PlAN_GRAPH_Z.PG_MEDICAMENT pgm WHERE pgm.POSITION_ID = 114049 GROUP BY pgm.MNN_NAME) as p,
(SELECT m.MNN_LIST_NAME as NAME, count(*) AS c FROM NOTIF_Z.MEDICINES m WHERE m.LOT_ID = 75842 GROUP BY m.MNN_LIST_NAME) AS n
WHERE p.NAME = n.NAME and  p.c != n.c;
